[project]
name = "ott.osm"
version = "1.0.0"
description = "Open Transit Tools - OTT Osm"
readme = "README.md"
requires-python = ">=3.12,<4.0"
license = "LicenseRef-Mozilla-derived"
authors = [
    { name = "Open Transit Tools", email = "info@opentransittools.org" },
]
keywords = ["ott", "osm", "otp", "gtfs", "gtfsdb", "data", "database", "services", "transit"]
classifiers = [
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP",
]
dependencies = [
    "simplejson",
    "shapely",
    "pyparsing",
    "sqlalchemy",
    "psycopg2",
    "protobuf",
    "osmread @ git+https://github.com/dezhin/osmread.git@master",
    "ott.utils @ git+https://github.com/OpenTransitTools/utils.git@master",
]

[project.urls]
Homepage = "http://opentransittools.com"
Repository = "https://github.com/OpenTransitTools/osm"

[project.scripts]
osm_clip_from_pbf = "ott.osm.osm_cache:clip_from_pbf"
osm_clip_rename = "ott.osm.osm_cache:clip_rename"
osm_update = "ott.osm.osm_cache:OsmCache.load"
osm_to_pgsql = "ott.osm.osm2pgsql.osm2pgsql:main"
osm_to_pbf = "ott.osm.pbf_tools:PbfTools.osm_to_pbf_cmdline"
osm_cull_transit = "ott.osm.pbf_tools:PbfTools.cull_transit_cmdline"
osm_stats = "ott.osm.stats.osm_info:OsmInfo.print_stats_via_cmdline"
osm_stats_cfg = "ott.osm.stats.osm_info:OsmInfo.print_stats_via_config"
osm_rename = "ott.osm.rename.osm_rename:main"
osm_make_raw = "ott.osm.osm_cache:make_raw_osm"
osm_other_exports = "ott.osm.osm_cache:OsmCache.exports"
osm_abbr_tester = "ott.osm.tests.osm_abbr_tester:main"
osm-intersections = "ott.osm.intersections.osm_to_intersections:main"
osm-intersections_cache = "ott.osm.osm_cache:OsmCache.intersections_cache"

[tool.poetry]
packages = [
    { include = "ott" },
]
include = [
    { path = "ott/osm/rename/config/*.csv", format = ["sdist", "wheel"] },
    { path = "ott/osm/osmosis/tagtransform.xml", format = ["sdist", "wheel"] },
    { path = "ott/osm/osm2pgsql/styles/*", format = ["sdist", "wheel"] },
    { path = "ott/osm/osm2pgsql/sql/*", format = ["sdist", "wheel"] },
]

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
test = [
    "pytest (>=9.0.2,<10.0.0)"
]
